// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC481fp7MQ-GFt_Ge-c1ND8paioufH3now',
    appId: '1:196082562425:web:f9303d8aaf11217067aba8',
    messagingSenderId: '196082562425',
    projectId: 'ala-elnota',
    authDomain: 'ala-elnota.firebaseapp.com',
    storageBucket: 'ala-elnota.firebasestorage.app',
    measurementId: 'G-7ZG8TLJCPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaxdlMwPoVJJ0MXSqxshtpgdUFpU9vjdo',
    appId: '1:196082562425:android:0bdd8cdadcef2a4567aba8',
    messagingSenderId: '196082562425',
    projectId: 'ala-elnota',
    storageBucket: 'ala-elnota.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFCtNE2lxoTrsGZXKkZ_GLJHu3i3am4wI',
    appId: '1:196082562425:ios:a3b1e62e542d868267aba8',
    messagingSenderId: '196082562425',
    projectId: 'ala-elnota',
    storageBucket: 'ala-elnota.firebasestorage.app',
    iosBundleId: 'com.example.alaElnota',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFCtNE2lxoTrsGZXKkZ_GLJHu3i3am4wI',
    appId: '1:196082562425:ios:a3b1e62e542d868267aba8',
    messagingSenderId: '196082562425',
    projectId: 'ala-elnota',
    storageBucket: 'ala-elnota.firebasestorage.app',
    iosBundleId: 'com.example.alaElnota',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC481fp7MQ-GFt_Ge-c1ND8paioufH3now',
    appId: '1:196082562425:web:f1b851bc85afb36f67aba8',
    messagingSenderId: '196082562425',
    projectId: 'ala-elnota',
    authDomain: 'ala-elnota.firebaseapp.com',
    storageBucket: 'ala-elnota.firebasestorage.app',
    measurementId: 'G-ZC50H5Z83D',
  );
}
